Repository Team-Daengnyang/moneynyang-server, pull requests merged in 2024-08, with the labels that each got.

#6 [FEAT] 회원가입
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/member/entity/Member.java
  src/main/java/com/fav/daengnyang/domain/member/repository/MemberRepository.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/CreatedRequest.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/MemberBankRequest.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/dummy.txt
  src/main/java/com/fav/daengnyang/domain/member/service/dto/response/LoginResponse.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/response/dummy.txt
  src/main/java/com/fav/daengnyang/global/auth/dto/MemberAuthority.java
  src/main/java/com/fav/daengnyang/global/auth/utils/JWTProvider.java
  src/main/java/com/fav/daengnyang/global/config/TimeConfig.java
  src/main/java/com/fav/daengnyang/global/config/WebConfig.java
  src/main/java/com/fav/daengnyang/global/dummy.txt
  src/main/java/com/fav/daengnyang/global/web/dto/response/SuccessResponse.java
  src/main/resources/application.properties
Labels: FEAT, 아영

#15 [FIX] accessToken 수정
  src/main/java/com/fav/daengnyang/domain/member/service/dto/MemberService.java
  src/main/java/com/fav/daengnyang/global/auth/dto/MemberAuthority.java
  src/main/java/com/fav/daengnyang/global/auth/utils/JWTProvider.java
Labels: FIX, 아영

#17 [FEAT] 계좌 생성
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/entity/Bankbook.java
  src/main/java/com/fav/daengnyang/domain/bankbook/repository/BankbookRepository.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/request/BankbookRequest.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/request/dummy.txt
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/response/BankbookResponse.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/response/dummy.txt
Labels: FEAT, 승빈, 금융

#22 [FIX] 금융 API 예외 처리 코드 수정
  src/main/java/com/fav/daengnyang/domain/member/service/dto/MemberService.java
  src/main/java/com/fav/daengnyang/global/handler/ApiExceptionHandler.java
Labels: FIX, 아영

#23 [FEAT] 내 계좌 조회
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/response/BankbookCreateResponse.java
Labels: FEAT, 승빈, 금융

#24 [FEAT] 로그인
  build.gradle
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/member/repository/MemberRepository.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/LoginRequest.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/MemberBankRequest.java
  src/main/java/com/fav/daengnyang/global/exception/CustomException.java
  src/main/java/com/fav/daengnyang/global/exception/ErrorCode.java
  src/main/java/com/fav/daengnyang/global/handler/ApiExceptionHandler.java
  src/main/resources/application.properties
Labels: FEAT, 아영, 금융

#29 [FEAT] 계좌 커버 수정
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/entity/Bankbook.java
  src/main/java/com/fav/daengnyang/domain/bankbook/repository/BankbookRepository.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/request/ColorUpdateRequest.java
  src/main/java/com/fav/daengnyang/global/web/dto/response/SuccessResponse.java
Labels: FEAT, 승빈

#31 [FEAT] 계좌 데이터 조회 기능 구현과 이에 따른 컬럼 수정
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/entity/Bankbook.java
  src/main/java/com/fav/daengnyang/domain/bankbook/repository/BankbookRepository.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/request/BankbookRequest.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/response/BankbookCreateResponse.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/response/BankbookResponse.java
  src/main/java/com/fav/daengnyang/domain/bookdata/controller/BookdataController.java
  src/main/java/com/fav/daengnyang/domain/bookdata/entity/BankbookDetail.java
  src/main/java/com/fav/daengnyang/domain/bookdata/repository/BankbookDetailRepository.java
  src/main/java/com/fav/daengnyang/domain/bookdata/service/BookdataService.java
  src/main/java/com/fav/daengnyang/domain/bookdata/service/dto/response/BookdataSummaryResponse.java
Labels: FIX, 승빈

#33 [FEAT] 인터셉터 및 시큐리티 구현
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/member/entity/Member.java
  src/main/java/com/fav/daengnyang/domain/member/repository/MemberRepository.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/global/auth/AuthService.java
  src/main/java/com/fav/daengnyang/global/auth/dto/MemberAuthority.java
  src/main/java/com/fav/daengnyang/global/auth/dto/MemberPrincipal.java
  src/main/java/com/fav/daengnyang/global/auth/filter/JwtFilter.java
  src/main/java/com/fav/daengnyang/global/auth/utils/JWTProvider.java
  src/main/java/com/fav/daengnyang/global/config/SecurityConfig.java
  src/main/java/com/fav/daengnyang/global/exception/ErrorCode.java
  src/main/java/com/fav/daengnyang/global/exception/ExceptionHandlerFilter.java
  src/main/resources/application.properties
Labels: FEAT, 아영

#34 [FEAT] 저축 목표 목록 가져오기
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/entity/Target.java
  src/main/java/com/fav/daengnyang/domain/target/repository/TargetRepository.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/TargetResponse.java
Labels: FEAT, 수영

#36 [FEAT] 저축 목표 추가하기
  src/main/java/com/fav/daengnyang/domain/bankbook/entity/Bankbook.java
  src/main/java/com/fav/daengnyang/domain/bankbook/repository/BankbookRepository.java
  src/main/java/com/fav/daengnyang/domain/fan/controller/FanController.java
  src/main/java/com/fav/daengnyang/domain/fan/entity/Fan.java
  src/main/java/com/fav/daengnyang/domain/fan/repository/FanRepository.java
  src/main/java/com/fav/daengnyang/domain/fan/service/dto/FanService.java
  src/main/java/com/fav/daengnyang/domain/fan/service/dto/request/dummy.txt
  src/main/java/com/fav/daengnyang/domain/fan/service/dto/response/dummy.txt
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/request/CreateTargetRequest.java
Labels: FEAT, 수영

#37 [FEAT] 반려동물 등록하기
  src/main/java/com/fav/daengnyang/domain/member/entity/Member.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/pet/controller/PetController.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
  src/main/java/com/fav/daengnyang/domain/pet/repository/PetRepository.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/PetService.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/request/CreatedPetRequest.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/request/dummy.txt
Labels: FEAT, 아영

#39 [FEAT] 반려동물 정보 조회
  src/main/java/com/fav/daengnyang/domain/bankbook/repository/BankbookRepository.java
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/pet/controller/PetController.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
  src/main/java/com/fav/daengnyang/domain/pet/repository/PetRepository.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/PetService.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/response/GetPetResponse.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/response/dummy.txt
  src/main/java/com/fav/daengnyang/global/exception/ErrorCode.java
Labels: FEAT, 아영

#43 [FEAT] 펫 보험 상세 조회
  src/main/java/com/fav/daengnyang/domain/insurance/controller/InsuranceController.java
  src/main/java/com/fav/daengnyang/domain/insurance/service/dto/InsuranceService.java
  src/main/java/com/fav/daengnyang/domain/insurance/service/dto/response/InsuranceDetailResponse.java
  src/main/java/com/fav/daengnyang/global/exception/ErrorCode.java
Labels: FEAT, 아영

#45 [FIX] 토큰에 대한 계좌 코드 수정
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/request/BankbookRequest.java
Labels: FEAT, 승빈

#48 [FEAT] 내 정보 조회
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/response/MemberInfoResponse.java
Labels: FEAT, 승빈

#50 [FEAT] 내 계좌 거래내역 조회
  src/main/java/com/fav/daengnyang/domain/bankbook/controller/BankbookController.java
  src/main/java/com/fav/daengnyang/domain/bankbook/service/dto/BankbookService.java
  src/main/java/com/fav/daengnyang/domain/bookdata/service/dto/response/BankbookHistoryResponse.java
Labels: FEAT, 승빈

#49 [FEAT] 모든 목표 요약 정보 조회
  build.gradle
  src/main/java/com/fav/daengnyang/domain/bankbook/entity/Bankbook.java
  src/main/java/com/fav/daengnyang/domain/bookdata/entity/BookdataDetail.java
  src/main/java/com/fav/daengnyang/domain/bookdata/repository/BookdataRepository.java
  src/main/java/com/fav/daengnyang/domain/bookdata/service/BookdataService.java
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/entity/BankbookDetail.java
  src/main/java/com/fav/daengnyang/domain/target/repository/BankbookDetailRepository.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetSummaryService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/AchievedTargetInfoResponse.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/TargetSummaryResponse.java
  src/main/java/com/fav/daengnyang/global/config/WebConfig.java
Labels: FEAT, 수영

#54 [FEAT] 저축 목표에 입금하기(금융)
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/entity/Target.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/request/TargetTransferRequest.java
Labels: FEAT, 수영, 금융

#56 [FIX] insurance 오류 수정
  src/main/java/com/fav/daengnyang/domain/insurance/controller/InsuranceController.java
  src/main/java/com/fav/daengnyang/domain/insurance/entity/Insurance.java
  src/main/java/com/fav/daengnyang/domain/insurance/repository/InsuranceRepository.java
  src/main/java/com/fav/daengnyang/domain/insurance/service/InsuranceService.java
Labels: FIX, 아영

#58 [FIX] TargetDetail 변경부분 수정
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/controller/TargetDetailController.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/repository/TargetDetailRepository.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/TargetDetailService.java
Labels: FIX, 수영

#61 [FEAT] 내 계좌 정보 조회
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/repository/AccountCodeRepository.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/response/AccountInfoResponse.java
Labels: FEAT, 승빈

#62 [FEAT] 입금하기
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/global/transaction/service/TransactionService.java
  src/main/java/com/fav/daengnyang/global/transaction/service/dto/request/DepositHeaderRequest.java
Labels: FEAT, 아영, 금융

#67 [FIX] Member 엔티티에 있던 Pet 연결부분 삭제
  src/main/java/com/fav/daengnyang/domain/member/entity/Member.java
Labels: FIX, 수영

#70 [FEAT] 목표 삭제
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
Labels: FEAT, 수영, 금융

#74 [REFACTOR] createTarget, getTargets 에서 `@AuthenticationPrincipal` 사용
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
Labels: REFACTOR, 수영

#75 [REFACTOR] getTargetDetails에서 `@RequestParam` 으로 TargetId 가져오도록 수정
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
Labels: REFACTOR, 수영

#76 [FIX] Target Entity 수정
  src/main/java/com/fav/daengnyang/domain/target/entity/Target.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/request/CreateTargetRequest.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/TargetDetailResponse.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/TargetResponse.java
Labels: FIX, 수영

#79 [FIX] 회원가입 로직 테스트 후 수정
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/entity/Account.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/AccountRequest.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/response/AccountResponse.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/AccountCreationHeaderRequest.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
  src/main/java/com/fav/daengnyang/domain/pet/service/PetService.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/request/CreatedPetRequest.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/response/GetPetResponse.java
  src/main/java/com/fav/daengnyang/global/transaction/service/TransactionService.java
  src/main/java/com/fav/daengnyang/global/transaction/service/dto/request/DepositHeaderRequest.java
  src/main/java/com/fav/daengnyang/global/web/dto/response/TransactionUtil.java
Labels: FIX, 아영, 금융

#88 [FIX] 내 계좌 정보 조회하기 response body값 수정
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/response/AccountInfoResponse.java
Labels: FIX, 승빈

#86 [FEAT] 반려동물 이미지 S3 업로드
  build.gradle
  src/main/java/com/fav/daengnyang/domain/pet/controller/PetController.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
  src/main/java/com/fav/daengnyang/domain/pet/service/PetService.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/request/CreatedPetRequest.java
  src/main/java/com/fav/daengnyang/global/aws/service/AwsService.java
  src/main/java/com/fav/daengnyang/global/config/S3Config.java
  src/main/java/com/fav/daengnyang/global/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: FEAT, 아영

#92 [FIX] 내 계좌 정보 조회하기 response body값 수정
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/AccountCreateRequest.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/response/MemberInfoResponse.java
Labels: FIX, 승빈

#89 [FEAT] Chatbot ver.1 개발
  src/main/java/com/fav/daengnyang/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/fav/daengnyang/domain/chatbot/entity/Chatbot.java
  src/main/java/com/fav/daengnyang/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/com/fav/daengnyang/domain/chatbot/service/ChatbotService.java
  src/main/java/com/fav/daengnyang/domain/chatbot/service/dto/request/CreateMessageRequest.java
  src/main/java/com/fav/daengnyang/domain/chatbot/service/dto/response/MessageResponse.java
Labels: FEAT, 수영

#97 [FEAT] 캐시워크 일지 등록
  src/main/java/com/fav/daengnyang/domain/cashwalk/controller/CashwalkController.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/entity/Cashwalk.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/repository/CashwalkRepository.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/request/CashwalkRequest.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/request/dummy.txt
Labels: FEAT, 수영

#100 [FIX] 계좌 생성 코드 수정
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/AccountCreateRequest.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/response/AccountCreateResponse.java
Labels: FIX, 승빈

#103 [FEAT] 계좌에 색상과 이미지 생성
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/entity/Account.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/AccountCreateColorRequest.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/response/AccountCreateColorResponse.java
Labels: FEAT, 승빈

#104 [FEAT] 출금하기
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/TransferHeaderRequest.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/TransferRequest.java
  src/main/java/com/fav/daengnyang/global/transaction/service/TransactionService.java
Labels: FEAT, 아영, 금융

#106 [FEAT] 이번 달 작성한 캐시워크 일지 조회하기
  src/main/java/com/fav/daengnyang/domain/cashwalk/controller/CashwalkController.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/entity/Cashwalk.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/repository/CashwalkRepository.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/response/CashwalkResponse.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/response/dummy.txt
Labels: FEAT, 수영

#107 [FIX] 거래 내역 조회 수정
  src/main/java/com/fav/daengnyang/domain/targetDetail/controller/TargetDetailController.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/TargetDetailService.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/dto/request/TransactionDetailRequest.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/dto/response/TransactionDetailResponse.java
Labels: FIX, 승빈

#109 [FIX] ExceptionResponse data부분 수정
  src/main/java/com/fav/daengnyang/global/dto/response/ExceptionResponse.java
Labels: FIX, 승빈

#114 [FIX] 거래내역 조회 내림차순으로 수정 및 컬럼 추가
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/entity/Account.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/TargetDetailService.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/dto/response/TransactionDetailResponse.java
Labels: FIX, 승빈

#115 [FEAT] 반려동물 이미지 수정 API 개발
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/ImageUpdateRequest.java
  src/main/java/com/fav/daengnyang/domain/pet/entity/Pet.java
Labels: FEAT, 아영

#118 [FIX] 목표에 입금 및 목표 삭제 오류 수정
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/request/TransferHeaderRequest.java
Labels: FIX, 수영, 금융

#120 [FEAT] 완료된 목표에서 출금하기
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetSummaryService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
Labels: FEAT, 수영, 금융

#126 [FEAT] 이메일 중복 체크 API 구현
  src/main/java/com/fav/daengnyang/domain/member/controller/MemberController.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/request/CheckRequest.java
  src/main/java/com/fav/daengnyang/domain/pet/service/dto/response/CheckResponse.java
  src/main/java/com/fav/daengnyang/global/auth/filter/JwtFilter.java
  src/main/java/com/fav/daengnyang/global/config/SecurityConfig.java
Labels: FEAT, 아영, 금융

#130 [FIX] 계좌 커스텀 색상 수정
  src/main/java/com/fav/daengnyang/domain/account/entity/Account.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
Labels: FIX, 아영

#131 [FEAT] 일지 작성 시 사진도 함께 들어가도록 수정
  src/main/java/com/fav/daengnyang/domain/cashwalk/controller/CashwalkController.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/entity/Cashwalk.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/request/CashwalkRequest.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/request/CreateCashwalkRequest.java
Labels: FEAT, 수영

#133 [FEAT] 일지 조회 시 response에 image url 추가
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/response/CashwalkResponse.java
Labels: FEAT, 수영

#136 [FIX] 출금 시 더 이상 목표를 조회할 때 나오지 않도록 수정
  src/main/java/com/fav/daengnyang/domain/target/entity/Target.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
  src/main/java/com/fav/daengnyang/domain/target/service/dto/response/TargetResponse.java
Labels: FIX, 수영

#139 [FEAT] 계좌 메모 API 구현
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/global/transaction/service/TransactionService.java
  src/main/java/com/fav/daengnyang/global/transaction/service/dto/request/DepositHeaderRequest.java
Labels: FEAT, 아영, 금융

#140 [FEAT] 랜덤 이름 생성 API 구현
  src/main/java/com/fav/daengnyang/domain/account/controller/AccountController.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/account/service/dto/request/TransferRequest.java
  src/main/java/com/fav/daengnyang/domain/targetDetail/service/TargetDetailService.java
Labels: FEAT, 아영, 금융

#141 [FEAT] 목표 추천
  src/main/java/com/fav/daengnyang/domain/target/controller/TargetController.java
  src/main/java/com/fav/daengnyang/domain/target/entity/Target.java
  src/main/java/com/fav/daengnyang/domain/target/repository/TargetRepository.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
Labels: FEAT, 아영

#143 [FIX] 계좌 이미지 수정 API 수정
  src/main/java/com/fav/daengnyang/domain/account/entity/Account.java
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
Labels: FIX, 아영

#145 [FEAT] 반려일지 총 횟수와 활동기간별 작성률 조회하기
  src/main/java/com/fav/daengnyang/domain/cashwalk/controller/CashwalkController.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/repository/CashwalkRepository.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/CashwalkService.java
  src/main/java/com/fav/daengnyang/domain/cashwalk/service/dto/response/CashwalkStatsResponse.java
  src/main/java/com/fav/daengnyang/domain/member/service/MemberService.java
  src/main/java/com/fav/daengnyang/domain/member/service/dto/response/MemberInfoResponse.java
Labels: FEAT, 수영

#146 [FEAT] 입출금 계좌 memo 구현
  src/main/java/com/fav/daengnyang/domain/account/service/AccountService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetService.java
  src/main/java/com/fav/daengnyang/domain/target/service/TargetTransferService.java
Labels: FEAT, 아영, 금융
